### PR TITLE
Add osx build.

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by 183amir** [comment]
``` python
import: 'bob.io.audio'

Traceback (most recent call last):

  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 31, in <module>

    import bob.io.audio

  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/bob/io/audio/__init__.py", line 4, in <module>

    from ._library import *

ImportError: dlopen(/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/bob/io/audio/_library.so, 2): Library not loaded: /usr/local/lib/libltdl.7.dylib

  Referenced from: /Users/travis/miniconda3/envs/_test/lib/libsox.3.dylib

  Reason: image not found
```

**Comment by 183amir** [comment]
@pelson sorry to bother you with this but I am trying to build `bob.io.audio` on mac and while it is working, I am having troubles with `conda` dependency resolver.

What was the problem?
- probably sox was complied at the time that we had `brew` installed in `travis`. Here is the error:

```
Library not loaded: /usr/local/lib/libltdl.7.dylib

  Referenced from: /Users/travis/miniconda3/envs/_test/lib/libsox.3.dylib
```

How did I try to solve it?
- I pushed a new build number for sox to be compiled again.

What is the problem now?
- Sox `14.4.2-3` is pulled to build `bob.io.audio` but it is tested against sox `14.4.2-1`. This only happens in Python 2.7! See the log here: https://travis-ci.org/conda-forge/bob.io.audio-feedstock/jobs/130517007

What am I suggesting?
- To delete `sox` `14.4.2-{0,1,2}` from `conda-forge` channels in anaconda.org. They are not working in travis anyway.

**Comment by jakirkham** [comment]
Phil's out until next week FYI.

**Comment by jakirkham** [comment]
@ocefpaf, could you please take a look at removing these packages? They are linked against Homebrew and as such are unusable.

**Comment by ocefpaf** [comment]
Sure. Doing that now.

PS: @jakirkham I might have missed some "pings," if you are waiting for me to take action somewhere else please ping me again and I will do ASAP.

**Comment by ocefpaf** [comment]
@183amir I deleted all but `sox-14.4.2-3`. Let me know if that solves the issue.

**Comment by jakirkham** [comment]
> Sure. Doing that now.

Thanks.

> PS: @jakirkham I might have missed some "pings,"...

I know the feeling. 😉 Phil and I had this same conversation the other day so I actually added it as a discussion item to see if we could find better ways to track and organize these somehow. Do you want to just try dumping things to do in this issue ( https://github.com/conda-forge/staged-recipes/issues/161 ) so we can keep track.

> ...if you are waiting for me to take action somewhere else please ping me again and I will do ASAP.

Honestly, I'm not sure. 😆 I don't think so though.

Same story though. If there are things you are needing from me please let me know, my notifications are getting swamped.

**Comment by 183amir** [comment]
Looks like somebody already restarted the CIs. Thank you that fixed it.

**Pull request merged**
